### ISSUE TITLE
Ardougne Chests Have no Function

### ISSUE THREAD

**Issue by keskiso** [2006-Scape/2006Scape#221]
Title.
Tried 10 coin, 50 coin, Nature Rune. None work

**Comment by mrextremez** [comment]
Can you provide me with the coords?

**Comment by keskiso** [comment]
2674,3307 <-- 10 Coin chest
2674,3302 <-- Nature rune chest up the stairs

**Comment by Dark98** [comment]
Fixed By PR #534
