### ISSUE TITLE
Lumbrdige Bank Missing Walls

### ISSUE THREAD

**Issue by naclander** [2006-Scape/2006Scape#482]
Going to the Lumbridge bank on the roof only shows the bankers, but no actual walls.

**Comment by Dark98** [comment]
As far as I recall this is because there wasn't actually supposed to be bankers on lumbridge castle roof in the revision the server is currently based on, the bankers was added manually for convenience

**Comment by naclander** [comment]
Thanks for the explanation. I'll resolve this issue.
