### ISSUE TITLE
Stuck Al-Kharid warrior spawn

### ISSUE THREAD

**Issue by halogod35** [2006-Scape/2006Scape#550]
NPC ID: 18
NPC X,Y: 3302, 3167
![java_o3Xoi90ge4](https://user-images.githubusercontent.com/6503891/215007124-fe16baf6-c756-4c61-a401-20a9a15e78f5.png)

**Comment by MatthewBishop** [comment]
The spawn is located here: https://github.com/2006-Scape/2006Scape/blob/master/2006Scape%20Server/data/cfg/spawns.json#L8632-L8641 

The x and y coordinates within those lines just need to be changed to be within the room.
