### ISSUE TITLE
Tzhaar gem store sells gems for 0 tokkul

### ISSUE THREAD

**Issue by halogod35** [2006-Scape/2006Scape#602]
TzHaar-Hur-Rin's Ore and Gem Store sells things for 0 tokkul and you can't buy it for 0 tokkul

**Comment by MatthewBishop** [comment]
There are 3 tzhaar stores that use tokkul, these probably all needed coded for being special cases. 
https://oldschool.runescape.wiki/w/TzHaar-Mej-Roh%27s_Rune_Store
https://oldschool.runescape.wiki/w/TzHaar-Hur-Lek%27s_Ore_and_Gem_Store
https://oldschool.runescape.wiki/w/TzHaar-Hur-Tel%27s_Equipment_Store


If I am not mistaken, archery tickets, trading sticks, and castle wars tickets all use the same shop interface, so we will need to handle them in the same way. Does anyone know of any other shops from the time period that did not use GP as a currency?

**Comment by MatthewBishop** [comment]
Also, is it only the gem store that works incorrectly or is it also the other stores (rune/equipment/cwars/trading sticks/archery tickets)?

**Comment by Dark98** [comment]
It's not every item in the gem store that has this issue, just a few

**Comment by MatthewBishop** [comment]
Ah. This is a easy fix then. Thanks for clarifying!

**Comment by MatthewBishop** [comment]
fixed on https://github.com/2006-Scape/2006Scape/pull/609
