### ISSUE TITLE
Razmire's builder trade doesn't work (ID: 283)

### ISSUE THREAD

**Issue by halogod35** [2006-Scape/2006Scape#605]
He has two shops in the right click menu: one for the general store and the other for building supplies (for Construction, a skill not yet implemented). His general store works, but Razmire Builders Merchants does not work.

**Comment by MatthewBishop** [comment]
Just some additional notes:

**Comment by MatthewBishop** [comment]
general store is shop 89, the builders merchants is shop 283. Ill sort this in the morning.

**Comment by MatthewBishop** [comment]
NPC id is 1254. He is located at     "x": 3488, "y": 3296. Lemme check ingame to see what click option the building supplies uses.
